surveil:
  image: savoirfairelinux/surveil:0.7.0
  links:
   - mongo
   - influxdb
   - alignak
  ports:
   - "8080:8080"
  environment:
    PBR_VERSION: "PROD"
  command:
    bash -c "cd /opt/surveil && ./setup.sh && /opt/surveil/env/bin/python setup.py develop && sleep 20 && surveil-api"

alignak:
  build: container/alignak/
  links:
    - mongo
    - influxdb
    - drupal
  ports:
    - "7767:7767"
  volumes:
    - ./container/alignak/.ssh:/home/alignak/.ssh

mongo:
  image: mongo
  ports:
   - "27017:27017"
  command:
    "mongod --smallfiles"
  volumes:
    - ./container-data/mongodb:/data/db

influxdb:
  image: savoirfairelinux/influxdb:0.9.0-rc30
  environment:
    PRE_CREATE_DB: "db"
  ports:
    - "8083:8083"
  volumes:
    - ./container-data/influxdb:/data

grafana:
  image: savoirfairelinux/grafana:2.0.2
  environment:
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "db"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"
  ports:
    - "8887:80"
  links:
    - influxdb

surveilclient:
  build: container/surveilclient/
  links:
    - surveil
    - mongo
  environment:
    HOST_ADDR: "drupal"
    DRUPAL_ALIAS: "@drupal"
    JENKINS: "http://jenkins.nodejs.org/job/node-build-ubuntu-12.04"
    SELENIUM_SCENARIO: "drupal"

bansho:
  image: savoirfairelinux/bansho:0.8.0
  environment:
    BANSHO_BACKEND: "surveil"
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "db"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"
  ports:
    - "8888:8888"
  links:
    - surveil
    - grafana
