surveil:
  image: surveil/surveil:0.13.1
  links:
   - mongo
   - influxdb
   - alignak
  ports:
   - "5311:5311"
  environment:
    PBR_VERSION: "PROD"
  command:
    bash -c "cd /opt/surveil && ./setup.sh && /opt/surveil/env/bin/python setup.py develop && sleep 20 && surveil-api"

alignak:
  build: container/alignak/
  links:
    - mongo
    - influxdb
  ports:
    - "7767:7767"
  volumes:
    - ./container/alignak/ssh:/home/alignak/.ssh

mongo:
  image: mongo
  ports:
   - "27017:27017"
  command:
    "mongod --smallfiles"
  volumes:
    - ./container-data/mongodb:/data/db

influxdb:
  image: surveil/influxdb:0.9.1
  environment:
    PRE_CREATE_DB: "db"
  ports:
    - "8083:8083"
  volumes:
    - ./container-data/influxdb:/data

grafana:
  image: savoirfairelinux/grafana:2.0.2
  environment:
    GRAFANA_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
    GRAFANA_AUTH_PROXY_ENABLED: true
    GRAFANA_AUTH_PROXY_HEADER_NAME: grafana-user
  links:
    - influxdb

surveilclient:
  build: container/surveilclient/
  links:
    - surveil
    - mongo
  environment:
    HOST_ADDR: "drupal"
    DRUPAL_ALIAS: "@drupal"
    JENKINS: "http://jenkins-host/job/thejob/"
    SELENIUM_SCENARIO: "drupal"

bansho:
  image: surveil/bansho:0.14.0
  environment:
    BANSHO_BACKEND: "surveil"
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "db"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"
  ports:
    - "80:8888"
  links:
    - surveil
    - grafana
