surveil:
  image: savoirfairelinux/surveil:0.7.0
  links:
   - mongo
   - influxdb
   - alignak
  ports:
   - "8080:8080"
  environment:
    PBR_VERSION: "DEV"
  command:
    bash -c "cd /opt/surveil && ./setup.sh && /opt/surveil/env/bin/python setup.py develop && sleep 20 && surveil-api"

alignak:
  build: container/alignak/
  links:
    - mongo
    - influxdb
    - drupal
  ports:
    - "7767:7767"
  volumes:
    - ./gen/.ssh/id_rsa:/home/alignak/.ssh/id_rsa
    - ./gen/.ssh/id_rsa.pub:/home/alignak/.ssh/id_rsa.pub
    - ../monitoring-tools/plugins/check-drupal-cache:/plugins/drupal_cache
    - ../monitoring-tools/plugins/check-drupal-codebase:/plugins/drupal_codebase
    - ../monitoring-tools/plugins/check-drupal-cron:/plugins/drupal_cron
    - ../monitoring-tools/plugins/check-drupal-database:/plugins/drupal_database
    - ../monitoring-tools/plugins/check-drupal-extensions:/plugins/drupal_extensions
    - ../monitoring-tools/plugins/check-drupal-logging:/plugins/drupal_logging
    - ../monitoring-tools/plugins/check-drupal-security:/plugins/drupal_security
    - ../monitoring-tools/plugins/check-drupal-status:/plugins/drupal_status
    - ../monitoring-tools/plugins/check-drupal-views:/plugins/drupal_views
    - ../monitoring-tools/plugins/check-drupal-jenkins:/plugins/drupal_jenkins
    - ../monitoring-tools/plugins/check-http-load:/plugins/http_load
    - ../monitoring-tools/plugins/check-selenium:/plugins/selenium

drupal:
  image: savoirfairelinux/drupal-nrpe-docker:0.5.0
  links:
    - db:mysql
  ports:
    - "80:80"
  volumes:
    - ./gen/.ssh/id_rsa.pub:/home/nagios/.ssh/authorized_keys
    - /var/www/html/sites
    - /var/www/private
    - ../monitoring-tools/plugins/check-drupal-cache:/opt/drupal_cache
    - ../monitoring-tools/plugins/check-drupal-codebase:/opt/drupal_codebase
    - ../monitoring-tools/plugins/check-drupal-cron:/opt/drupal_cron
    - ../monitoring-tools/plugins/check-drupal-database:/opt/drupal_database
    - ../monitoring-tools/plugins/check-drupal-extensions:/opt/drupal_extensions
    - ../monitoring-tools/plugins/check-drupal-logging:/opt/drupal_logging
    - ../monitoring-tools/plugins/check-drupal-security:/opt/drupal_security
    - ../monitoring-tools/plugins/check-drupal-status:/opt/drupal_status
    - ../monitoring-tools/plugins/check-drupal-views:/opt/drupal_views
  environment:
    - UPLOAD_LIMIT=20M
    - MEMORY_LIMIT=128M
    - DB_NAME=drupal
    - DB_USER=root
    - DB_PASS=password
    - DB_HOST=mysql

mongo:
  image: mongo
  ports:
   - "27017:27017"
  command:
      "mongod --nojournal --smallfiles"

influxdb:
  image: savoirfairelinux/influxdb:0.9.0-rc30
  environment:
    PRE_CREATE_DB: "db"
  ports:
    - "8083:8083"

grafana:
  image: savoirfairelinux/grafana:2.0.2
  environment:
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "db"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"
  ports:
    - "8887:80"
  links:
    - influxdb

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /var/lib/mysql

surveilclient:
  build: container/surveilclient/
  links:
    - surveil
    - mongo
  volumes:
    - ../monitoring-tools/packs/linux-drupal/:/packs/linux-drupal/
